function calcEMA(p,n){const k=2/(n+1),r=[p[0]];for(let i=1;i<p.length;i++)r.push(p[i]*k+r[i-1]*(1-k));return r}
function calcRSI(p,n=14){if(p.length<n+1)return p.map(()=>50);const g=[],l=[];for(let i=1;i<p.length;i++){const d=p[i]-p[i-1];g.push(d>0?d:0);l.push(d<0?-d:0)}let ag=g.slice(0,n).reduce((a,b)=>a+b)/n,al=l.slice(0,n).reduce((a,b)=>a+b)/n;const r=new Array(n).fill(null);r.push(100-100/(1+ag/(al||1e-10)));for(let i=n;i<g.length;i++){ag=(ag*(n-1)+g[i])/n;al=(al*(n-1)+l[i])/n;r.push(100-100/(1+ag/(al||1e-10)))}return r}
function calcMACD(p){const f=calcEMA(p,12),s=calcEMA(p,26),ml=f.map((v,i)=>v-s[i]),sl=calcEMA(ml.slice(25),9),fsl=[...new Array(25).fill(null),...sl];return{ml,sl:fsl,h:ml.map((v,i)=>fsl[i]!=null?v-fsl[i]:null)}}
function calcBB(p,n=20,m=2){const u=[],mi=[],lo=[];for(let i=0;i<p.length;i++){if(i<n-1){u.push(null);mi.push(null);lo.push(null);continue}const sl=p.slice(i-n+1,i+1),mn=sl.reduce((a,b)=>a+b)/n,sd=Math.sqrt(sl.reduce((a,b)=>a+(b-mn)**2,0)/n);u.push(mn+m*sd);mi.push(mn);lo.push(mn-m*sd)}return{u,m:mi,l:lo}}
function calcATR(cs,n=14){const tr=cs.map((c,i)=>{if(!i)return c.h-c.l;const p=cs[i-1];return Math.max(c.h-c.l,Math.abs(c.h-p.c),Math.abs(c.l-p.c))});if(tr.length<n)return tr;let a=tr.slice(0,n).reduce((x,y)=>x+y)/n;const r=new Array(n-1).fill(null);r.push(a);for(let i=n;i<tr.length;i++){a=(a*(n-1)+tr[i])/n;r.push(a)}return r}
function calcCVD(cs){const r=[0];for(let i=1;i<cs.length;i++){const c=cs[i],rng=(c.h-c.l)||1e-10;r.push(r[r.length-1]+c.v*(2*(c.c-c.l)/rng-1))}return r}
function detectStruct(cs){if(cs.length<20)return'ranging';const rc=cs.slice(-20),h1=Math.max(...rc.slice(0,10).map(c=>c.h)),h2=Math.max(...rc.slice(10).map(c=>c.h)),l1=Math.min(...rc.slice(0,10).map(c=>c.l)),l2=Math.min(...rc.slice(10).map(c=>c.l));if(h2>h1&&l2>l1)return'uptrend';if(h2<h1&&l2<l1)return'downtrend';return'ranging'}
function detectPats(cs){if(cs.length<2)return[];const c=cs[cs.length-1],p=cs[cs.length-2],bd=Math.abs(c.c-c.o),pBd=Math.abs(p.c-p.o),rng=(c.h-c.l)||1e-10,uw=c.h-Math.max(c.o,c.c),lw=Math.min(c.o,c.c)-c.l,r=[];if(bd<rng*.1)r.push('Doji');if(c.c>c.o&&p.c<p.o&&c.o<=p.c&&c.c>=p.o)r.push('Bullish Engulfing');if(c.c<c.o&&p.c>p.o&&c.o>=p.c&&c.c<=p.o)r.push('Bearish Engulfing');if(lw>bd*2&&lw>uw*2&&bd>0)r.push('Bullish Pin Bar');if(uw>bd*2&&uw>lw*2&&bd>0)r.push('Bearish Pin Bar');if(c.h<p.h&&c.l>p.l){if(p.c<p.o&&c.c>c.o)r.push('Bullish Harami');if(p.c>p.o&&c.c<c.o)r.push('Bearish Harami')}if(p.c>p.o&&pBd>(p.h-p.l)*0.5&&c.o>=p.c&&c.h>p.h&&c.c<p.o+(p.c-p.o)/2)r.push('Dark Cloud Cover');if(p.c<p.o&&pBd>(p.h-p.l)*0.5&&c.o<=p.c&&c.l<p.l&&c.c>p.c+(p.o-p.c)/2)r.push('Piercing Line');return r}
function findPivots(cs,w=5){const highs=[],lows=[];for(let i=w;i<cs.length-w;i++){let isH=true,isL=true;const c=cs[i];for(let j=1;j<=w;j++){if(cs[i-j].h>=c.h||cs[i+j].h>=c.h)isH=false;if(cs[i-j].l<=c.l||cs[i+j].l<=c.l)isL=false}if(isH)highs.push({i,p:c.h,t:c.t});if(isL)lows.push({i,p:c.l,t:c.t})}return{highs,lows}}
function detectGeometric(pivots){const{highs,lows}=pivots,r=[],vP=0.015;if(highs.length>=2){const h1=highs[highs.length-2],h2=highs[highs.length-1];if(Math.abs(h1.p-h2.p)/h1.p<=vP)r.push('Double Top')}if(lows.length>=2){const l1=lows[lows.length-2],l2=lows[lows.length-1];if(Math.abs(l1.p-l2.p)/l1.p<=vP)r.push('Double Bottom')}if(highs.length>=3){const s1=highs[highs.length-3],head=highs[highs.length-2],s2=highs[highs.length-1];if(head.p>s1.p&&head.p>s2.p&&Math.abs(s1.p-s2.p)/s1.p<=vP)r.push('Head and Shoulders')}if(lows.length>=3){const s1=lows[lows.length-3],head=lows[lows.length-2],s2=lows[lows.length-1];if(head.p<s1.p&&head.p<s2.p&&Math.abs(s1.p-s2.p)/s1.p<=vP)r.push('Inverse Head & Shoulders')}return r}
function findSR(cs,lb=30){const rc=cs.slice(-lb);return{res:Math.max(...rc.map(c=>c.h)),sup:Math.min(...rc.map(c=>c.l))}}
function calcADX(cs,n=14){if(cs.length<n*2)return cs.map(()=>null);const pd=[],nd=[],tr=[];for(let i=1;i<cs.length;i++){const p=cs[i-1],c=cs[i],up=c.h-p.h,dn=p.l-c.l;pd.push(up>dn&&up>0?up:0);nd.push(dn>up&&dn>0?dn:0);tr.push(Math.max(c.h-c.l,Math.abs(c.h-p.c),Math.abs(c.l-p.c)))}const pS=[],nS=[],tS=[],dx=[];let ps=0,ns=0,ts=0;for(let i=0;i<pd.length;i++){if(i<n){ps+=pd[i];ns+=nd[i];ts+=tr[i];if(i===n-1){pS.push(ps);nS.push(ns);tS.push(ts)}}else{ps=ps-ps/n+pd[i];ns=ns-ns/n+nd[i];ts=ts-ts/n+tr[i];pS.push(ps);nS.push(ns);tS.push(ts)}}for(let i=0;i<pS.length;i++){const pi=100*pS[i]/(tS[i]||1),ni=100*nS[i]/(tS[i]||1),sm=pi+ni;dx.push(sm===0?0:100*Math.abs(pi-ni)/sm)}const r=new Array(n*2-1).fill(null);let ax=dx.slice(0,n).reduce((a,b)=>a+b)/n;r.push(ax);for(let i=n;i<dx.length;i++){ax=(ax*(n-1)+dx[i])/n;r.push(ax)}return r}
function calcVWAP(cs){const r=[];let cv=0,cvp=0;for(let i=0;i<cs.length;i++){const t=(cs[i].h+cs[i].l+cs[i].c)/3,v=cs[i].v||1;cv+=v;cvp+=t*v;r.push(cvp/cv)}return r}
function findOBs(cs,atrs){const obs={bullish:null,bearish:null};for(let i=cs.length-2;i>=5;i--){const atr=atrs[i]||((cs[i].h-cs[i].l)||1e-10),c=cs[i];if(!obs.bullish&&c.c-c.o>1.8*atr){const ob=cs[i-1];if(ob.c<ob.o){let inv=false;for(let j=i+1;j<cs.length;j++){if(cs[j].c<ob.l){inv=true;break}}if(!inv)obs.bullish={top:ob.h,bot:ob.l}}}if(!obs.bearish&&c.o-c.c>1.8*atr){const ob=cs[i-1];if(ob.c>ob.o){let inv=false;for(let j=i+1;j<cs.length;j++){if(cs[j].c>ob.h){inv=true;break}}if(!inv)obs.bearish={top:ob.h,bot:ob.l}}}if(obs.bullish&&obs.bearish)break}return obs}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { calcEMA, calcRSI, calcMACD, calcBB, calcATR, calcCVD, detectStruct, detectPats, findPivots, detectGeometric, findSR, calcADX, calcVWAP, findOBs };
}
